from rest_framework import serializers

class PredictInputSerializer(serializers.Serializer):
    Age = serializers.IntegerField()
    CGPA = serializers.FloatField()
    Suicidal_thoughts = serializers.IntegerField()
    Work_Study_Hours = serializers.IntegerField()
    Family_History_of_Mental_Illness = serializers.IntegerField()
    Sleep_Duration_Less_than_5_hours = serializers.IntegerField()
    Dietary_Habits_Unhealthy = serializers.IntegerField()
    Dietary_Habits_Healthy = serializers.IntegerField()
    degree_group_Bachelor = serializers.IntegerField()
    degree_group_Master = serializers.IntegerField()
    degree_group_School = serializers.IntegerField()
    Financial_Stress_Category_Low = serializers.IntegerField()
    Financial_Stress_Category_High = serializers.IntegerField()
    Financial_Stress_Category_Very_High = serializers.IntegerField()
    region_South = serializers.IntegerField()
    region_East = serializers.IntegerField()
    region_North = serializers.IntegerField()
    region_West = serializers.IntegerField()
    Study_Satisfaction_Category_Neutral = serializers.IntegerField()
    Study_Satisfaction_Category_Very_Dissatisfied = serializers.IntegerField()
    Study_Satisfaction_Category_Very_Satisfied = serializers.IntegerField()
    Academic_Pressure_Category_High_Pressure = serializers.IntegerField()
    Academic_Pressure_Category_Very_High_Pressure = serializers.IntegerField()
    Academic_Pressure_Category_Low_Pressure = serializers.IntegerField()
